name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -o ./build/experimental

    - name: Test
      run: go test -v ./...
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: experimental
        path: build/
      
  deploy:
    name: Deploy #Job name
    needs: build # The build job has to run successfully for the deploy job to run
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: experimental
        path: build/
    - name: List files
      run: ls -R
    - name: SSHPASS Github Action
      # You may pin to the exact commit or the version.
      # uses: matheusvanzan/sshpass-action@1e96f05518c2e99d17587ee85fa4d64c1612d0f1
      uses: matheusvanzan/sshpass-action@v1
      with:
        # SSHPASS host
        host: 89.252.140.247
        # SSHPASS username
        username: root
        # SSHPASS password
        password: ${{ secrets.SERVERPASS }}
        # SSHPASS commands to run
        run: sshpass scp build/experimental root@89.252.140.247:/home/

